name: "Bind DNS Server"
version: "20260226053153"
slug: "bind"
description: "A fully featured DNS server. Please note: This addon is not provided by Internet Systems Consortium, it is a third party addon"
url: "https://github.com/Zajsoft/addon-bind_fa"
host_network: true
arch:
  - aarch64
  - amd64
init: false
ports:
  53/udp: 5353
  53/tcp: 5353
map:
  - addon_config:rw
image: ghcr.io/cmsj/{arch}-addon-bind
backup_exclude:
  - '*/cache'
